"""
FINRA AI Framework compliance rules.

Each function is a pure rule with signature:
    (text: str, metadata: dict) -> Optional[ComplianceViolation]

Rules:
    FINRA-001  Suitability Check
    FINRA-002  Disclosure Requirement
    FINRA-003  Supervision Obligation
    FINRA-004  No Misleading Outputs
"""

from __future__ import annotations

import re
from typing import Optional

from src.compliance.models import ComplianceViolation, Severity

# ---------------------------------------------------------------------------
# FINRA-001: Suitability Check
# ---------------------------------------------------------------------------

# Keywords that indicate investment advice without suitability context
_ADVICE_KEYWORDS = re.compile(
    r"\b(you should (buy|sell|invest|purchase|hold)|"
    r"i recommend (buying|selling|investing|purchasing)|"
    r"best investment|guaranteed return|sure (bet|thing)|"
    r"definitely (buy|sell|invest)|"
    r"(buy|sell|invest) now)\b",
    re.IGNORECASE,
)

# Suitability qualifiers that indicate proper context
_SUITABILITY_QUALIFIERS = re.compile(
    r"\b(based on your (risk tolerance|financial situation|goals|profile|objectives)|"
    r"suitable for|appropriate for|given your|"
    r"depending on your|subject to suitability|"
    r"consult (a|your) (financial advisor|advisor|professional))\b",
    re.IGNORECASE,
)


def check_suitability(text: str, metadata: dict) -> Optional[ComplianceViolation]:
    """FINRA-001: Detect AI-generated advice that lacks suitability basis.

    Triggers when investment advice language is present but no suitability
    qualifier is found.
    """
    if not text or not text.strip():
        return None

    has_advice = bool(_ADVICE_KEYWORDS.search(text))
    has_qualifier = bool(_SUITABILITY_QUALIFIERS.search(text))

    if has_advice and not has_qualifier:
        return ComplianceViolation(
            policy_domain="FINRA",
            rule_id="FINRA-001",
            rule_name="Suitability Check",
            severity=Severity.HIGH,
            description=(
                "Investment advice detected without suitability basis. "
                "AI-generated recommendations must be grounded in the client's "
                "risk tolerance, financial situation, and investment objectives."
            ),
            remediation_suggestion=(
                "Add explicit suitability context referencing the client's risk "
                "profile, financial goals, and investment objectives before making "
                "any investment recommendation."
            ),
        )
    return None


# ---------------------------------------------------------------------------
# FINRA-002: Disclosure Requirement
# ---------------------------------------------------------------------------

_AI_DISCLOSURE_PATTERNS = re.compile(
    r"\b(generated by (ai|artificial intelligence|an? (ai|llm|language model))|"
    r"ai-generated|this (is|was) (produced|created|generated) by|"
    r"automated (advice|recommendation|analysis)|"
    r"ai (advisor|assistant|system) (says|recommends|suggests))\b",
    re.IGNORECASE,
)

# Contexts where disclosure is required (output to end-user)
_ADVICE_OR_RECOMMENDATION = re.compile(
    r"\b(recommend|advise|suggest|propose|should (buy|sell|invest|hold)|"
    r"investment (advice|recommendation|plan|strategy))\b",
    re.IGNORECASE,
)


def check_disclosure(text: str, metadata: dict) -> Optional[ComplianceViolation]:
    """FINRA-002: Flag outputs missing required AI disclosure language.

    When the output contains investment recommendations, it must include
    disclosure that the content was AI-generated.
    """
    if not text or not text.strip():
        return None

    # Only check outputs that contain advice/recommendations
    has_recommendation = bool(_ADVICE_OR_RECOMMENDATION.search(text))
    if not has_recommendation:
        return None

    has_disclosure = bool(_AI_DISCLOSURE_PATTERNS.search(text))
    # Also accept disclosure in metadata
    if not has_disclosure and metadata.get("ai_disclosure") is not True:
        return ComplianceViolation(
            policy_domain="FINRA",
            rule_id="FINRA-002",
            rule_name="Disclosure Requirement",
            severity=Severity.HIGH,
            description=(
                "Investment recommendation output is missing required AI disclosure. "
                "FINRA requires that AI-generated advice be clearly identified as such."
            ),
            remediation_suggestion=(
                "Prepend or append a disclosure statement such as: "
                "'This recommendation was generated by an AI system and should be "
                "reviewed by a qualified financial advisor before acting upon it.'"
            ),
        )
    return None


# ---------------------------------------------------------------------------
# FINRA-003: Supervision Obligation
# ---------------------------------------------------------------------------

_AUTOMATED_ACTION_PATTERNS = re.compile(
    r"\b(automatically (executed|placed|submitted|processed)|"
    r"auto-(execute|trade|rebalance|invest)|"
    r"executed without (human|advisor|review)|"
    r"no (human|advisor|review) (required|needed|necessary)|"
    r"fully automated (trade|order|recommendation|execution))\b",
    re.IGNORECASE,
)

_SUPERVISION_INDICATORS = re.compile(
    r"\b(pending (approval|review|confirmation)|"
    r"requires (human|advisor|supervisor) (approval|review|sign-off)|"
    r"subject to (review|approval|supervision)|"
    r"human-in-the-loop|awaiting approval)\b",
    re.IGNORECASE,
)


def check_supervision(text: str, metadata: dict) -> Optional[ComplianceViolation]:
    """FINRA-003: Detect unsupervised automated recommendations.

    Triggers when automated execution language is present without supervision
    indicators, or when metadata explicitly marks the action as unsupervised.
    """
    if not text or not text.strip():
        return None

    has_automated = bool(_AUTOMATED_ACTION_PATTERNS.search(text))
    has_supervision = bool(_SUPERVISION_INDICATORS.search(text))

    # Also check metadata flag
    unsupervised_flag = metadata.get("unsupervised_execution", False)

    if (has_automated and not has_supervision) or unsupervised_flag:
        return ComplianceViolation(
            policy_domain="FINRA",
            rule_id="FINRA-003",
            rule_name="Supervision Obligation",
            severity=Severity.HIGH,
            description=(
                "Automated recommendation or trade execution detected without "
                "evidence of human supervision. FINRA requires broker-dealers to "
                "supervise all automated investment recommendations."
            ),
            remediation_suggestion=(
                "Ensure all automated recommendations are routed through a "
                "human-in-the-loop approval step before execution. "
                "Add supervision indicators to the output."
            ),
        )
    return None


# ---------------------------------------------------------------------------
# FINRA-004: No Misleading Outputs
# ---------------------------------------------------------------------------

_MISLEADING_PATTERNS = re.compile(
    r"\b(guaranteed (return|profit|gain|income|yield)|"
    r"risk-free (investment|return|profit)|"
    r"always (profitable|gains|returns)|"
    r"never (loses?|fails?)|"
    r"100% (safe|secure|guaranteed|certain)|"
    r"(will|shall) (definitely|certainly|always) (increase|grow|rise|profit)|"
    r"no (risk|downside|loss possible))\b",
    re.IGNORECASE,
)


def check_no_misleading_outputs(text: str, metadata: dict) -> Optional[ComplianceViolation]:
    """FINRA-004: Flag statistically unsupported or misleading claims.

    Detects absolute guarantees, risk-free claims, and other misleading
    language that is not statistically supportable.
    """
    if not text or not text.strip():
        return None

    if _MISLEADING_PATTERNS.search(text):
        return ComplianceViolation(
            policy_domain="FINRA",
            rule_id="FINRA-004",
            rule_name="No Misleading Outputs",
            severity=Severity.HIGH,
            description=(
                "Output contains statistically unsupported or misleading claims "
                "such as guaranteed returns or risk-free investments. "
                "FINRA prohibits misleading statements in investment communications."
            ),
            remediation_suggestion=(
                "Remove absolute guarantees and risk-free claims. "
                "Replace with probabilistic language and include appropriate "
                "risk disclosures (e.g., 'past performance does not guarantee "
                "future results')."
            ),
        )
    return None


# ---------------------------------------------------------------------------
# Public registry of all FINRA rules
# ---------------------------------------------------------------------------

FINRA_RULES: list[tuple[str, object]] = [
    ("FINRA-001", check_suitability),
    ("FINRA-002", check_disclosure),
    ("FINRA-003", check_supervision),
    ("FINRA-004", check_no_misleading_outputs),
]
